apiVersion: v1
kind: Namespace
metadata:
  name: flask-server

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-client
  namespace: flask-server
  labels:
    app: flask-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-client
  template:
    metadata:
      labels:
        app: flask-client
    spec:
      containers:
        - name: flask-client-container
          image: usman476/demo-flask-app:latest
          command: [ "python3" ]
          args: [ "multi_request.py",  "-a", "192.168.222.187",  "-d", "mysql",  "-n", "sensor-pipeline",  "-s", "100",  "-l", "merge",  "-r", "100"]
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          imagePullPolicy: "Always"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-3