apiVersion: apps/v1
kind: Deployment
metadata:
  name: coap-clients
  namespace: coap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coap-clients
  template:
    metadata:
      labels:
        app: coap-clients
    spec:
      containers:
      - name: coap-client
        image: usman476/coap:latest
        env:
        - name: COAP_SERVER_URI
          value: "coap-svc.coap-server.svc.cluster.local"
        - name: COAP_CLIENTS
          value: "2"
        command: [ "python3" ]
        args: [ "coap-client.py" ]
        imagePullPolicy: "Always"

