apiVersion: apps/v1
kind: Deployment
metadata:
  name: coap-server
#  namespace: coap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coap-svc
  template:
    metadata:
      labels:
        app: coap-svc
    spec:
      containers:
      - name: coap-server
        image: usman476/coap:latest
        command: [ "python3" ]
        args: [ "coap-server.py" ]
        imagePullPolicy: "Always"

---
apiVersion: v1
kind: Service
metadata:
  name: coap-svc
spec:
  selector:
    app: coap-svc
  ports:
  - protocol: UDP
    port: 5683
    targetPort: 5683
