---
apiVersion: v1
kind: Namespace
metadata:
  name: file-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-server-deployment
  namespace: file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
      - name: file-server
        image: usman476/file-server:latest
        imagePullPolicy: "Always"
        command: [ "python3" ]
        args: [ "file-server.py" ]
        volumeMounts:
        - name: files-volume
          mountPath: /files

      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
      restartPolicy: Always
      volumes:
        - name: files-volume
          hostPath:
            path: /home/aida/files
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
  namespace: file-server
spec:
  type: NodePort
  selector:
    app: file-server
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30201
      name: fs-port