---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
  labels:
    environment: production
    app: locust-normal-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-deploy
  template:
    metadata:
      labels:
        app: locust-deploy
    spec:
      containers:
      - name: locust-container
        image: usman476/stress-test:latest
        command: [ "sleep" ]
        args: [ "infinity" ]
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker4
