---
apiVersion: v1
kind: Pod
metadata:
  name: mqtt-stresser-pod
  namespace: uc0
  labels:
    environment: development
    app: mqtt-stresser-pod
spec:
  containers:
  - name: mqtt-stresser-container
    image: flaviostutz/mqtt-stresser:latest
    #command: []
    args: ["-broker", "tcp://mqtt-mosquitto.uc0.svc.cluster.local:1883", "-num-clients", "100", "-num-messages", "10", "-rampup-delay", "1s", "-rampup-size", "10", "-global-timeout", "180s", "-timeout", "20s"]
    imagePullPolicy: "IfNotPresent"
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: worker-vm-1