---
apiVersion: batch/v1
kind: Job
metadata:
  name: data-generator-job
  labels:
    environment: production
    app: data-generator-job
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: data-generator-container
        image: usman476/mqtt-kafka-faust:latest
        command: ["python3"]
        args: ["generator.py", "--data_type", "both", "--value_type", "anomaly", "--start_value", "0.0", "--end_value", "9.99", "--total_values", "1000", "--output_file", "generated_values.csv"]
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /data
          name: data-volume
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: worker2
      volumes:
      - name: data-volume
        hostPath:
          # directory location on host
          path: /opt/data
          # this field is optional
          type: Directory