{
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(host)" } },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Node Power & Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temp_temp{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}} - {{sensor}}"
    },
    {}
   ]
  },
  {
   "title": "Node Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "powerstat_package_current_power_consumption_watts{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "intel_powerstat_current_power_consumption_watts{host=~\"^$Node$\",job=\"telegraf\",package_id=\"0\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Node-level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_idle{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - idle",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - user"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - system"
    },
    {
     "expr": "cpu_usage_iowait{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - iowait"
    },
    {
     "expr": "cpu_usage_steal{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - steal"
    },
    {
     "expr": "cpu_usage_guest{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - guest"
    },
    {
     "expr": "cpu_usage_guest_nice{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - guest_nice"
    },
    {
     "expr": "cpu_usage_irq{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - irq"
    },
    {
     "expr": "cpu_usage_softirq{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu-total\"}",
     "legendFormat": "{{host}} - softirq"
    }
   ]
  },
  {
   "title": "Systeml Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "system_load1{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load1"
    },
    {
     "expr": "system_load5{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load5"
    },
    {
     "expr": "system_load15{host=~\"^$Node$\",job=\"telegraf\"}",
     "legendFormat": "{{host}} - load15"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu0\"}",
     "legendFormat": "{{host}} - {{cpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu1\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu2\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu3\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu4\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu5\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu6\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_system{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu7\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu0\"}",
     "legendFormat": "{{host}} - {{cpu}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu1\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu2\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu3\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu4\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu5\"}",
     "legendFormat": "{{host}} - {{cpu}} "
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu6\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    },
    {
     "expr": "cpu_usage_user{host=~\"^$Node$\", job=\"telegraf\", cpu=\"cpu7\"}",
     "legendFormat": "{{host}} - {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "mem_total{host=~\"^$Node$\", job=\"telegraf\"} - mem_available{host=~\"^$Node$\", job=\"telegraf\"}",
     "legendFormat": "{{host}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "disk_used_percent{host=~\"^$Node$\", job=\"telegraf\", device=~\"vda.*|sda.*|nvme.*|mmcblk0p2|mapper.*\"}",
     "legendFormat": "{{host}} - {{device}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DiskIO (Read_bytes/Write_bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - reads"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "- rate(diskio_write_bytes{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - writes",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "DiskIO (io_time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=~\"^$Node$\", job=\"telegraf\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{name}}"
    }
   ]
  },
  {
   "title": "DiskIO (read/write time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(diskio_write_time{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} - reads"
    },
    {
     "expr": "- rate(diskio_read_time{host=~\"^$Node$\", job=\"telegraf\"}[$__interval])",
     "legendFormat": "{{host}} -writes"
    }
   ]
  },
  {
   "title": "Data Rate (uplink/downlink)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "rate(net_bytes_sent{host=~\"^$Node$\", job=\"telegraf\", interface=~\"^eno.*|^enp.*|^ens.*|^eth.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{interface}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "- rate(net_bytes_recv{host=~\"^$Node$\", job=\"telegraf\", interface=~\"^eno.*|^enp.*|^ens.*|^eth.*\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Namespace-wide Pod-level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods Running",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(kubernetes_pod_container_memory_usage_bytes{host=~\"^$Node$\", namespace=~\"^$Namespace$\"}) by (host, pod_name))"
      }
     ]
    },
    {
     "title": "Pods CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum (rate (kubernetes_pod_container_cpu_usage_nanocores{host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m]))",
       "legendFormat": "{{host}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Pods Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "expr": "sum (kubernetes_pod_container_memory_usage_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"})",
       "legendFormat": "{{host}}",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Pods Network Usage",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (kubernetes_pod_network_rx_bytes{job=\"telegraf\",host=~\"^$Node$\", namespace=~\"^$Namespace$\"}[1m]))"
      }
     ]
    }
   ]
  }
 ]
}