apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-deployment-normal
  labels:
    environment: production
    app: mqtt-publisher-normal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mqtt-publisher-normal
  template:
    metadata:
      labels:
        app: mqtt-publisher-normal
    spec:
      containers:
      - name: publisher-normal-container
        image: usman476/mqtt-kafka-faust:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STRESS_APP
          value: "False"
        - name: STRESS_CPU
          value: "0"
        - name: STRESS_VM
          value: "1"
        - name: STRESS_VM_BYTES
          value: "50M"
        - name: STRESS_HDD
          value: "0"
        - name: STRESS_IO
          value: "0"
        - name: STRESS_TIMEOUT
          value: "120s"
        - name: IDLE_TIMEOUT
          value: "30"
        - name: STRESS_INIT_DELAY
          value: "30"
        command: ["python3"]
        args: ["publisher/publisher.py",
               "--value_type", "normal",
               "--data_type", "both",
               "--mqtt_broker", "mqtt-mosquitto.uc2.svc.cluster.local",
               "--mqtt_broker_port", "1883",
               "--thingsboard_token", "sensor-normal-token",
               "--mqtt_topic", "mqtt/temperature/data",
               "--thingsboard_publisher", "false",
               "--sensors", "10",
               "--delay_type", "fixed",
               "--delay_start_range", "0",
               "--delay_end_range", "10.0",
               "--delay", "1.0",
               "--invalid_value_occurrence", "10",
               "--invalid_value", "19",
               "--normal_input_file", "normal_data.csv",
               "--abnormal_input_file", "abnormal_data.csv"
        ]
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - mountPath: /data
          name: data-volume
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker1
      volumes:
      - name: data-volume
        hostPath:
          # directory location on host
          path: /opt/data
          # this field is optional
          type: Directory
