apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-subscriber-deployment
  labels:
    environment: production
    app: mqtt-subscriber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-subscriber-deployment
  template:
    metadata:
      labels:
        app: mqtt-subscriber-deployment
    spec:
      containers:
      - name: mqtt-subscriber-container
        image: usman476/mqtt-kafka-faust:latest
        env:
        - name: MQTT_BROKER
          value: "mqtt-mosquitto.uc2.svc.cluster.local"
        - name: MQTT_BROKER_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: "mqtt/temperature/readings"
        - name: KAFKA_BROKER
          value: "bitnami-kafka-0.bitnami-kafka-headless.uc2.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "temperature-readings"
        command: ["python3"]
        args: ["subscriber/subscriber.py"]
        imagePullPolicy: "Always"
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker1