apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-analyzer-deployment
  labels:
    environment: production
    app: temp-analyzer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp-analyzer-deployment
  template:
    metadata:
      labels:
        app: temp-analyzer-deployment
    spec:
      containers:
      - name: temp-analyzer-container
        image: usman476/mqtt-kafka-faust:latest
        env:
        - name: MQTT_BROKER
          value: "mqtt-mosquitto.uc1.svc.cluster.local"
        - name: MQTT_BROKER_PORT
          value: "1883"
        - name: MQTT_ACTUATOR_TOPIC
          value: "mqtt/temperature/actions"
        - name: THINGSBOARD_DEVICE_TOKEN
          value: "3CvCfOphVy9DnnpqVTzT"
        - name: KAFKA_BROKER
          value: "bitnami-kafka-headless.uc1.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "temperature-readings"
        - name: VALID_VALUE_RANGE_START
          value: "0"
        - name: VALID_VALUE_RANGE_END
          value: "10"
        - name: MIN_THRESHOLD_VALUE
          value: "2"
        - name: MAX_THRESHOLD_VALUE
          value: "8"
        - name: SAVE_DATA
          value: "file"
        - name: DATABASE_URL
          value: "mysql.uc1.svc.cluster.local"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent.observability.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: TRACE_SAMPLING_RATE
          value: "100"
        #- name: DATABASE_URL
        #  value: "cassandra-0.cassandra-headless.uc1.svc.cluster.local"
        command: ["python3"]
        args: ["analyzer/temp-analyzer.py", "worker", "-l", "info"]
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /analyzer
          name: temperature-analyzer-volume
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker2
      volumes:
      - name: temperature-analyzer-volume
        hostPath:
          # directory location on host
          path: /opt/data
          # this field is optional
          type: Directory