[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
req_extensions     = req_ext
distinguished_name = dn

[ dn ]
C  = SE
ST = Varmland
L  = Karlstad
O  = KaU
CN = DNS_NAME

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = DNS_NAME
IP.1  = IP_ADDRESS
