apiVersion: v1
kind: Pod
metadata:
  name: thingsboard-stresser-pod
spec:
  containers:
  - name: thingsboard-stresser-container
    image: thingsboard/tb-ce-performance-test:latest
    env:
      - name: REST_URL
        value: "http://x.x.x.x:30181"
      - name: MQTT_HOST
        value: "thingsboard-mqtt.thingsboard.svc.cluster.local"
      - name: MQTT_PORT
        value: "1883"
      - name: REST_USERNAME
        value: "user@gmail.com"
      - name: REST_PASSWORD
        value: "123456"
      - name: DEVICE_END_IDX
        value: "1111"
      - name: MESSAGES_PER_SECOND
        value: "5"
      - name: DURATION_IN_SECONDS
        value: "300"
      - name: ALARMS_PER_SECOND
        value: "1"
      - name: DEVICE_CREATE_ON_START
        value: "true"
      - name: TEST_PAYLOAD_TYPE
        value: "SMART_METER"
      - name: DEVICE_DELETE_ON_COMPLETE
        value: "true"
      - name: log-driver
        value: "none"
      - name: debug
        value: "true"
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: worker1