apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-ui-app
  labels:
    environment: production
    app: web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ui-app
  template:
    metadata:
      labels:
        app: web-ui-app
    spec:
      containers:
      - name: flask-server
        image: usman476/web-ui:latest
        ports:
          - containerPort: 5000
        env:
        - name: MYSQL_URL
          value: "mysql://root:root@mysql.sensor-pipeline.svc.cluster.local/iiot"
        - name: REFRESH_INTERVAL
          value: "60"  # Set your desired refresh interval
        - name: DATA_RANGE
          value: "3600"  # Set your desired data range
        command: ["python3"]
        args: ["app.py"]
        imagePullPolicy: "Always"
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: worker1

---
apiVersion: v1
kind: Service
metadata:
  name: web-ui-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30041  # Choose any available port number
  selector:
    app: web-ui-app
