apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/pg
  claimRef:
    namespace: thingsboard
    name: postgres-pv-claim
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-zk-1
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/zk
  claimRef:
    namespace: thingsboard
    name: data-zookeeper-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-zk-2
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/zk
  claimRef:
    namespace: thingsboard
    name: datalog-zookeeper-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-kafka-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: //opt/persistent-volumes/kafka
  claimRef:
    namespace: thingsboard
    name: logs-tb-kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-kafka-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/kafka
  claimRef:
    namespace: thingsboard
    name: app-logs-tb-kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-kafka-3
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/kafka
  claimRef:
    namespace: thingsboard
    name: config-tb-kafka-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-mqtt-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/mqtt
  claimRef:
    namespace: thingsboard
    name: logs-tb-mqtt-transport-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-mqtt-2
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/mqtt
  claimRef:
    namespace: thingsboard
    name: logs-tb-mqtt-transport-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-coap-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/coap
  claimRef:
    namespace: thingsboard
    name: logs-tb-coap-transport-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tb-http-1
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/persistent-volumes/http
  claimRef:
    namespace: thingsboard
    name: logs-tb-http-transport-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - worker2