---
apiVersion: v1
kind: Pod
metadata:
  name: mqtt-stresser-pod
  namespace: uc2
  labels:
    environment: development
    app: mqtt-stresser-pod
spec:
  containers:
  - name: mqtt-stresser-container
    image: flaviostutz/mqtt-stresser:latest
    command: ["mqtt-stresser"]
    #args: ["10000"]
    args: ["-broker", "tcp://mqtt-mosquitto.uc2.svc.cluster.local:1883", "-num-clients", "50", "-num-messages", "100000", "-rampup-delay", "1s", "-rampup-size", "100", "-global-timeout", "360s", "-timeout", "20s"]
    imagePullPolicy: "IfNotPresent"
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: worker2